### ISSUE TITLE
Feature Request: Support for categories

### ISSUE THREAD

**Issue by hatorikibble** [preaction/Log-Any-Adapter-Log4perl#3]
Often you have one Log4perl configuration file which defines multiple categories with associated Logfiles:

```
log4perl.category.PackageA      = DEBUG, A1
log4perl.appender.A1          = Log::Log4perl::Appender::File
log4perl.appender.A1.filename = /var/log/package_a.log
[...]
log4perl.category.PackageB      = DEBUG, A2
log4perl.appender.A2          = Log::Log4perl::Appender::File
log4perl.appender.A2.filename = /var/log/package_b.log
```

and then you select the category with  `get_logger("PackageA")`. It would be nice if `Log::Any::Adapter::Log4perl` could work with this behaviour.

**Comment by cazador481** [comment]
I have code all over the place that does.  
Example code
my $category="foo";
my $log=Log::Any->get_logger(category=>$category);
$log->debug("this will print from category $category");

Take a look at MooX::Log::Any for more example code.

**Comment by preaction** [comment]
Adapters are stored on a per-category basis, and each instance of an adapter has a category. I've just written a test that verifies that Log::Any categories are correctly mapped to Log::Log4perl categories, so this works already.
